### ISSUE TITLE
A question mark?

### ISSUE THREAD

**Issue by zvikaro** [weiweihuanghuang/GaugeTool#5]
Hi there,
Can’t figure out why Gauge Tool (Hey, amazing tool indeed!) is showing a question mark in the middle of the oval tool. It used to have 2 colors - not anymore.

**Comment by zvikaro** [comment]
Never before have I defined a custom parameter for Gauge tool. I will try that

**Comment by zvikaro** [comment]
Thanks. I created a custom parameter as you suggested. Nothing. Happens in every glyph.
![screen shot 2018-07-30 at 13 37 20](https://user-images.githubusercontent.com/18307787/43392890-be482d28-93fd-11e8-9d1f-d334c8d82883.png)

**Comment by weiweihuanghuang** [comment]
Hmm, strange. Can I get a look at the .glyphs file, feel free to delete the contents of all the glyphs. Also that parameter looks like its in the instance rather than the Master?

**Comment by zvikaro** [comment]
Thanks, now that I moved the parameter to the Master it works again.
I must admit that until today, all I did was to write the 2 values (H stem and V stem) in the note tab and all was perfect. Isn’t this way enough anymore?

Best,
Zvika

We Will Win<https://youtu.be/JSMqh2Nut_E>

**Comment by zvikaro** [comment]
Hebrew + Latin

Best,
Zvika

We Will Win<https://youtu.be/JSMqh2Nut_E>

**Comment by weiweihuanghuang** [comment]
I see, so for the Latin, it should read the dimensions palette, for the Hebrew, I'm not sure what the dimensions palette looks like?

**Comment by zvikaro** [comment]
It looks just similar to Latin.
![screen shot 2018-07-31 at 18 16 10](https://user-images.githubusercontent.com/18307787/43468986-dc9b4058-94ed-11e8-82ca-5b685050f031.png)

**Comment by weiweihuanghuang** [comment]
I have no idea what's wrong. Can you send me your .glyphs file (delete all the outlines) and the version of your glyphs app.

**Comment by weiweihuanghuang** [comment]
I think you're replying to the GitHub emails which doesn't actually email attachments to me, please email to wweeiihhuuaanngg@gmail.com

**Comment by weiweihuanghuang** [comment]
Ok I see what the issue is, it is because you are working on Hebrew script and the plugin doesn't have a reference in the Dimensions panel to display a ball, but which dimension would you use? The `H O n o t` for hebrew ??

**Comment by zvikaro** [comment]
I just tried to:


1.       Fill all references in a font I work on now.

2.       Add the to the note tab

3.       Add a custom parameter to the Master tab.
Still a vague oval with a question mark.

I think something was changed in the last version. My work flow is the same as before, always using the note tab an all used to be colorful and beautiful.


Best,
Zvika

We Will Win<https://youtu.be/JSMqh2Nut_E>

**Comment by weiweihuanghuang** [comment]
It's not using the note tab anymore because each master needs it's own settings. 

You said up there that the custom parameter worked, now it doesn't? You can download the previous version if you want: https://github.com/weiweihuanghuang/GaugeTool/tree/a9dd10897e99965c38f7f8b74046d4933fe1ea96

**Comment by zvikaro** [comment]
Sure, thanks – I will give it a shot.


Best,
Zvika

We Will Win<https://youtu.be/JSMqh2Nut_E>

**Comment by zvikaro** [comment]
Thanks for your kind support.

Now that I changed my work flow to set a custom parameter it all works just fine.


Best,
Zvika

We Will Win<https://youtu.be/JSMqh2Nut_E>
